// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using angular_dotnet.DbContext;

#nullable disable

namespace angular_dotnet.Migrations
{
    [DbContext(typeof(GrocerContext))]
    [Migration("20221218032544_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("angular_dotnet.DbModels.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StoreSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreSectionId");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "",
                            Name = "Canned Corn",
                            StoreSectionId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Unit = "Medium Can"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Carrots, Potatoes, Green Beans, Onions version",
                            Name = "Canned Veg All",
                            StoreSectionId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Unit = "Large Can"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "16 ounces",
                            Name = "Canned Diced Potatoes",
                            StoreSectionId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Unit = "Medium Can"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "",
                            Name = "Ground Turkey",
                            StoreSectionId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Unit = "Pound"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "16 ounces",
                            Name = "Enchilada Sauce",
                            StoreSectionId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Unit = "Medium Can"
                        });
                });

            modelBuilder.Entity("angular_dotnet.DbModels.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Vegetable Soup",
                            Url = "https://ochsners.us"
                        });
                });

            modelBuilder.Entity("angular_dotnet.DbModels.RecipeIngredientJunction", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("IngredientCount")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredientJunction");

                    b.HasData(
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngredientCount = 1
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngredientCount = 1
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngredientCount = 1
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngredientCount = 2
                        },
                        new
                        {
                            IngredientId = new Guid("00000000-0000-0000-0000-000000000005"),
                            RecipeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IngredientCount = 3
                        });
                });

            modelBuilder.Entity("angular_dotnet.DbModels.StoreSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoreSection");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Produce"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Canned"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Breakfast"
                        });
                });

            modelBuilder.Entity("angular_dotnet.DbModels.Ingredient", b =>
                {
                    b.HasOne("angular_dotnet.DbModels.StoreSection", "StoreSection")
                        .WithMany()
                        .HasForeignKey("StoreSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreSection");
                });

            modelBuilder.Entity("angular_dotnet.DbModels.RecipeIngredientJunction", b =>
                {
                    b.HasOne("angular_dotnet.DbModels.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredientJunction")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredientJunction_IngredientId");

                    b.HasOne("angular_dotnet.DbModels.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("angular_dotnet.DbModels.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredientJunction");
                });
#pragma warning restore 612, 618
        }
    }
}
